package ent;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

// Generated Apr 8, 2012 2:02:16 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name="user_type")
@XmlRootElement
public class UserType implements java.io.Serializable {

    /** . */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private String name;
    //private String name1;

  

    public UserType() {
    }

    public UserType(Integer id) {
        this.id = id;
    }
    public UserType(Integer id, String name) {
        this.id = id;
        this.name = name;
    }
    public UserType(String name) {
        this.name = name;
    }
    
    @Id
    @GeneratedValue
    @Column(name="ID")
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="NAME", nullable = false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
//    public String getName1() {
//        return name1;
//    }
//
//    public void setName1(String name1) {
//        this.name1 = name1;
//    }
//    @Column(name="NAME1", nullable = false)
//    public void setName(String name) {
//        this.name = name;
//    }

}
